name: Deploy to Amazon ECS

on:
  workflow_dispatch: # Manual trigge
    input:
    branches:
      - main
      - dev

env:
  AWS_REGION: MY_AWS_REGION            

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: ${{ env.REGION }}
